### PR TITLE
Burn-in on the yellow text

### PR DESCRIPTION
**Pull request by Tw1stedL0gic**
Fixed a nice burn-in so it looks more like a digital watch.

### CODE REVIEW

**Comment by Tw1stedL0gic** [comment]
This might result in merge conflict. But since it's just two images it should be easily fixed. In worst case just keep the "sprite - yellow.png" and ignore the original sprite.

**Comment by skrhlm** [comment]
ONE CANNOT SIMPLY MERGE A PSD

**Comment by Tw1stedL0gic** [comment]
It's a png! But just delete one of them, yao.

**Comment by Tw1stedL0gic** [comment]
Nu borde det gå att mergea utan problem!

**Pull request merged**
